### ISSUE TITLE
ModuleNotFoundError: No module named 'himawaripy'

### ISSUE THREAD

**Issue by Mustela-sibirica** [boramalper/himawaripy#104]
hi, I just installed it in Ubuntu 18.04, 
GNOME Shell 3.28.3,

And I just updated  python3-setuptools,
return "Finished processing dependencies for himawaripy==2.0.1".

But, when I type "himawaripy", I got massage :
`Traceback (most recent call last):
  File "/home/sun/anaconda3/bin/himawaripy", line 11, in <module>
    load_entry_point('himawaripy==2.0.1', 'console_scripts', 'himawaripy')()
  File "/home/sun/anaconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 487, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/sun/anaconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2728, in load_entry_point
    return ep.load()
  File "/home/sun/anaconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2346, in load
    return self.resolve()
  File "/home/sun/anaconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2352, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
ModuleNotFoundError: No module named 'himawaripy'
`

**Comment by boramalper** [comment]
Hi, would you mind installing the latest version and trying again?

```bash
python3 -m pip install --user himawaripy==2.2.0
```
