### ISSUE TITLE
Windows failure： Bash not found

### ISSUE THREAD

**Issue by tommix626** [boramalper/himawaripy#121]
PS D:\git\himawaripy> python3 himawaripy --auto-offset
himawaripy 2.2.0
Updating...
Latest version: 2021/06/11 13:30:00 GMT.
Detected offset: UTC+08:00
Offset version: 2021/06/11 11:30:00 GMT.
Downloading tiles...
Downloading tiles: 1/16 completed...
Downloading tiles: 2/16 completed...
Downloading tiles: 3/16 completed...
Downloading tiles: 4/16 completed...
Downloading tiles: 5/16 completed...
Downloading tiles: 6/16 completed...
Downloading tiles: 7/16 completed...
Downloading tiles: 8/16 completed...
Downloading tiles: 9/16 completed...
Downloading tiles: 10/16 completed...
Downloading tiles: 11/16 completed...
Downloading tiles: 12/16 completed...
Downloading tiles: 13/16 completed...
Downloading tiles: 14/16 completed...
Downloading tiles: 15/16 completed...
Downloading tiles: completed.
Saving to 'C:\Users\Tom\AppData\Local\himawaripy\Cache\himawari-20210611T113000.png'...
'bash' 不是内部或外部命令，也不是可运行的程序
或批处理文件。( is neither a command nor executable)
Could NOT retrieve env. var. DBUS_SESSION_BUS_ADDRESS
'bash' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
Could NOT retrieve env. var. DISPLAY
Exception in thread himawaripy-main-thread:
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1520.0_x64__qbz5n2kfra8p0\lib\threading.py", line 954, in _bootstrap_inner
    self.run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1520.0_x64__qbz5n2kfra8p0\lib\threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "D:\git\himawaripy\himawaripy\__main__.py", line 214, in thread_main
    r = set_background(output_file)
  File "C:\Users\Tom\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\himawaripy\utils.py", line 92, in set_background
    elif has_program("feh"):
  File "C:\Users\Tom\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\himawaripy\utils.py", line 199, in has_program
    subprocess.check_output(["which", "--", program])
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1520.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1520.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1520.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1520.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 1420, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] 系统找不到指定的文件。

**Comment by tommix626** [comment]
win10 terminal python3.9

**Comment by tommix626** [comment]
when changing the wallpaper somehow it went wrong but the downloading is successful

**Comment by jasonho1308** [comment]
Windows don't have bash

**Comment by tommix626** [comment]
So Is there a way to let it work on windows' python terminal?

**Comment by jasonho1308** [comment]
You may try this #118

**Comment by tommix626** [comment]
Thank you! I'll give it a try
