### ISSUE TITLE
Problem with KDE 5.27.4

### ISSUE THREAD

**Issue by ALutz273** [boramalper/himawaripy#127]
System: 

```
        #####           hostname
       #######          ------------- 
       ##O#O##          OS: AlmaLinux 9.2 (Turquoise Kodkod) x86_64 
       #######          Host: 21HH002WGE ThinkPad T16 Gen 2 
     ###########        Kernel: 5.14.0-284.30.1.el9_2.x86_64 
    #############       Uptime: 1 day, 2 hours, 56 mins 
   ###############      Packages: 1672 (rpm), 18 (flatpak) 
   ################     Shell: bash 5.1.8 
  #################     Resolution: 3840x1600 
#####################   DE: Plasma 5.27.4 
#####################   WM: kwin 
  #################     Theme: [Plasma], Breeze [GTK2/3] 
                        Icons: [Plasma], breeze-dark [GTK2/3] 
                        Terminal: konsole 
                        CPU: 13th Gen Intel i7-1355U (12) @ 5.000GHz 
                        GPU: Intel Raptor Lake-P [Iris Xe Graphics] 
                        Memory: 14364MiB / 31748MiB 

```

Errorlog: 
```
Plasma version 'plasmashell 5.27.4
'.
Exception in thread himawaripy-main-thread:
Traceback (most recent call last):
  File "/usr/lib64/python3.9/threading.py", line 980, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.9/threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "/home/andre/.local/lib/python3.9/site-packages/himawaripy/__main__.py", line 214, in thread_main
    r = set_background(output_file)
  File "/home/andre/.local/lib/python3.9/site-packages/himawaripy/utils.py", line 76, in set_background
    subprocess.check_output(
  File "/usr/lib64/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib64/python3.9/subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib64/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib64/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'qdbus'

```

**Comment by skyywj** [comment]
小严同学已收到您的邮件，

**Comment by ALutz273** [comment]
change utils.py an now it works 

from:


```
                try:
                    subprocess.check_output(
                        [
                            "qdbus",
                            "org.kde.plasmashell",
                            "/PlasmaShell",
                            "org.kde.PlasmaShell.evaluateScript",
                            script.format(file_path),
                        ]
                    )
```

to:

```
                try:
                    subprocess.check_output(
                        [
                            "qdbus-qt5",
                            "org.kde.plasmashell",
                            "/PlasmaShell",
                            "org.kde.PlasmaShell.evaluateScript",
                            script.format(file_path),
                        ]
                    )
```

**Comment by manjaroer** [comment]
Can you tell me where exactly utils.py is located?
