### ISSUE TITLE
Cannot start himawaripy with Python 3.12.5

### ISSUE THREAD

**Issue by manjaroer** [boramalper/himawaripy#129]
It seems himawaripy script (as well as goes16-background script) doesn't work on the latest distros with Python 3.12.5 and pip 24.2. (KDE PLASMA 5.27 and 6.X.X.) It still works on Debian 12 Stable, MX-Linux, but not on Arch, Manjaro, EndeavourOS, OpenSUSE Thumbleweed, Fedora 39-40.

It generates the following error:
=================================
imawaripy 2.2.0
Updating...
Latest version: 2024/09/10 21:00:00 GMT.
Detected offset: UTC+03:00
Offset version: 2024/09/10 14:00:00 GMT.
Downloading tiles...
Downloading tiles: 1/16 completed...
Downloading tiles: 2/16 completed...
Downloading tiles: 3/16 completed...
Downloading tiles: 4/16 completed...
Downloading tiles: 5/16 completed...
Downloading tiles: 6/16 completed...
Downloading tiles: 7/16 completed...
Downloading tiles: 8/16 completed...
Downloading tiles: 9/16 completed...
Downloading tiles: 10/16 completed...
Downloading tiles: 11/16 completed...
Downloading tiles: 12/16 completed...
Downloading tiles: 13/16 completed...
Downloading tiles: 14/16 completed...
Downloading tiles: 15/16 completed...
Downloading tiles: completed.
Saving to '/home/alex/.cache/himawaripy/himawari-20240910T140000.png'...
grep: /proc//environ: Нет такого файла или каталога
Could NOT retrieve env. var. GNOME_DESKTOP_SESSION_ID
Plasma version 'plasmashell 6.1.4
'.
Exception in thread himawaripy-main-thread:
Traceback (most recent call last):
  File "/usr/lib/python3.12/threading.py", line 1075, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.12/threading.py", line 1012, in run
    self._target(*self._args, **self._kwargs)
  File "/home/alex/.local/lib/python3.12/site-packages/himawaripy/__main__.py", line 214, in thread_main
    r = set_background(output_file)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alex/.local/lib/python3.12/site-packages/himawaripy/utils.py", line 76, in set_background
    subprocess.check_output(
  File "/usr/lib/python3.12/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.12/subprocess.py", line 1955, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'qdbus'
================================================================THE END OF THE ERROR MESSAGE

WHAT IS NEEDED?
A HERO is needed who can fix the issue of this beautiful and unique script, and make it workable of the latest distros and KDE Plasma 6.

**Comment by skyywj** [comment]
小严同学已收到您的邮件，

**Comment by manjaroer** [comment]
I used himawaripy 2.2.0 and added try:
                            "qdbus-qt5"
to ~/himawaripy/himawaripy/utils.py file...
For no awail. The issue is still here.
PLEASE, HELP! ) The script is really BEAUTIFUL (as well as goes16-background). DO NOT DROP IT ! )

**Comment by manjaroer** [comment]
And yes, when I install the script
python3 -m pip install --user himawaripy
I HAVE TO BREAK SYSTEM PACKAGES!
Because I get the following message:
============================================================
 This environment is externally managed
╰─> To install Python packages system-wide, try 'pacman -S
    python-xyz', where xyz is the package you are trying to
    install.
    
    If you wish to install a non-Arch-packaged Python package,
    create a virtual environment using 'python -m venv path/to/venv'.
    Then use path/to/venv/bin/python and path/to/venv/bin/pip.
    
    If you wish to install a non-Arch packaged Python application,
    it may be easiest to use 'pipx install xyz', which will manage a
    virtual environment for you. Make sure you have python-pipx
    installed via pacman.

note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
hint: See PEP 668 for the detailed specification.
========================================================THE END OF THE MESSAGE
