### ISSUE TITLE
urllib.error.URLError: <urlopen error [Errno -3] Temporary failure in name resolution>`

### ISSUE THREAD

**Issue by AbuMaia** [boramalper/himawaripy#71]
Ubuntu 16.04.1 LTS 64-bit
Gnome Shell 3.18.5

`abumaia@AbuMaia:~$ himawaripy
Updating...
Latest version: 2016/08/05 03:30:00 GMT
Offset version: 2016/08/04 11:30:00 GMT

Downloading tiles: 5/16 completedmultiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.5/urllib/request.py", line 1254, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/usr/lib/python3.5/http/client.py", line 1106, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python3.5/http/client.py", line 1151, in _send_request
    self.endheaders(body)
  File "/usr/lib/python3.5/http/client.py", line 1102, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python3.5/http/client.py", line 934, in _send_output
    self.send(msg)
  File "/usr/lib/python3.5/http/client.py", line 877, in send
    self.connect()
  File "/usr/lib/python3.5/http/client.py", line 849, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/usr/lib/python3.5/socket.py", line 693, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/usr/lib/python3.5/socket.py", line 732, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 119, in worker
    result = (True, func(_args, *_kwds))
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 44, in mapstar
    return list(map(_args))
  File "/usr/local/lib/python3.5/dist-packages/himawaripy-1.1-py3.5.egg/himawaripy/himawaripy.py", line 53, in download_chunk
    with urlopen(url_format.format(level, width, strftime("%Y/%m/%d/%H%M%S", latest), x, y)) as tile_w:
  File "/usr/lib/python3.5/urllib/request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 466, in open
    response = self._open(req, data)
  File "/usr/lib/python3.5/urllib/request.py", line 484, in _open
    '_open', req)
  File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(_args)
  File "/usr/lib/python3.5/urllib/request.py", line 1282, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/usr/lib/python3.5/urllib/request.py", line 1256, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno -3] Temporary failure in name resolution>
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/himawaripy", line 9, in <module>
    load_entry_point('himawaripy==1.1', 'console_scripts', 'himawaripy')()
  File "/usr/local/lib/python3.5/dist-packages/himawaripy-1.1-py3.5.egg/himawaripy/himawaripy.py", line 88, in main
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 260, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 608, in get
    raise self._value
urllib.error.URLError: <urlopen error [Errno -3] Temporary failure in name resolution>
abumaia@AbuMaia:~$ nc himawari8.nict.go.jp 80
abumaia@AbuMaia:~$ curl http://himawari8-dl.nict.go.jp/himawari8/img/D531106/latest.json
{"date":"2016-08-05 03:30:00","file":"PI_H08_20160805_0330_TRC_FLDK_R10_PGPFD.png"}`

**Comment by ottlinger** [comment]
I seem to be having the same problem with Ubuntu ....
```
$ himawaripy 
himawaripy 2.0.1
Updating...
Latest version: 2017/07/25 20:10:00 GMT.
Downloading tiles...
[1/3] Retrying to download 'http://himawari8.nict.go.jp/img/D531106/4d/550/2017/07/25/201000_3_3.png'...
[1/3] Retrying to download 'http://himawari8.nict.go.jp/img/D531106/4d/550/2017/07/25/201000_2_1.png'...
[1/3] Retrying to download 'http://himawari8.nict.go.jp/img/D531106/4d/550/2017/07/25/201000_1_0.png'...
Downloading tiles: 1/16 completed...
[1/3] Retrying to download 'http://himawari8.nict.go.jp/img/D531106/4d/550/2017/07/25/201000_2_2.png'...
[1/3] Retrying to download 'http://himawari8.nict.go.jp/img/D531106/4d/550/2017/07/25/201000_3_0.png'...
[1/3] Retrying to download 'http://himawari8.nict.go.jp/img/D531106/4d/550/2017/07/25/201000_1_2.png'...
Downloading tiles: 2/16 completed...
[1/3] Retrying to download 'http://himawari8.nict.go.jp/img/D531106/4d/550/2017/07/25/201000_3_1.png'...
[1/3] Retrying to download 'http://himawari8.nict.go.jp/img/D531106/4d/550/2017/07/25/201000_0_0.png'...
[1/3] Retrying to download 'http://himawari8.nict.go.jp/img/D531106/4d/550/2017/07/25/201000_0_1.png'...
[1/3] Retrying to download 'http://himawari8.nict.go.jp/img/D531106/4d/550/2017/07/25/201000_3_2.png'...
[1/3] Retrying to download 'http://himawari8.nict.go.jp/img/D531106/4d/550/2017/07/25/201000_2_3.png'...
[1/3] Retrying to download 'http://himawari8.nict.go.jp/img/D531106/4d/550/2017/07/25/201000_2_0.png'...
[1/3] Retrying to download 'http://himawari8.nict.go.jp/img/D531106/4d/550/2017/07/25/201000_1_3.png'...
[1/3] Retrying to download 'http://himawari8.nict.go.jp/img/D531106/4d/550/2017/07/25/201000_1_1.png'...
[1/3] Retrying to download 'http://himawari8.nict.go.jp/img/D531106/4d/550/2017/07/25/201000_0_2.png'...
[2/3] Retrying to download 'http://himawari8.nict.go.jp/img/D531106/4d/550/2017/07/25/201000_1_0.png'...
Downloading tiles: 3/16 completed...
Downloading tiles: 4/16 completed...
Downloading tiles: 5/16 completed...
Downloading tiles: 6/16 completed...
Downloading tiles: 7/16 completed...
[1/3] Retrying to download 'http://himawari8.nict.go.jp/img/D531106/4d/550/2017/07/25/201000_0_3.png'...
[2/3] Retrying to download 'http://himawari8.nict.go.jp/img/D531106/4d/550/2017/07/25/201000_1_2.png'...
Downloading tiles: 8/16 completed...
Downloading tiles: 9/16 completed...
[2/3] Retrying to download 'http://himawari8.nict.go.jp/img/D531106/4d/550/2017/07/25/201000_2_3.png'...
[2/3] Retrying to download 'http://himawari8.nict.go.jp/img/D531106/4d/550/2017/07/25/201000_1_1.png'...
[2/3] Retrying to download 'http://himawari8.nict.go.jp/img/D531106/4d/550/2017/07/25/201000_3_2.png'...
Downloading tiles: 10/16 completed...
[2/3] Retrying to download 'http://himawari8.nict.go.jp/img/D531106/4d/550/2017/07/25/201000_1_3.png'...
[2/3] Retrying to download 'http://himawari8.nict.go.jp/img/D531106/4d/550/2017/07/25/201000_0_0.png'...
[2/3] Retrying to download 'http://himawari8.nict.go.jp/img/D531106/4d/550/2017/07/25/201000_0_3.png'...
Downloading tiles: 11/16 completed...
[2/3] Retrying to download 'http://himawari8.nict.go.jp/img/D531106/4d/550/2017/07/25/201000_0_1.png'...
Downloading tiles: 12/16 completed...
Downloading tiles: 13/16 completed...
[3/3] Retrying to download 'http://himawari8.nict.go.jp/img/D531106/4d/550/2017/07/25/201000_3_2.png'...
[3/3] Retrying to download 'http://himawari8.nict.go.jp/img/D531106/4d/550/2017/07/25/201000_0_0.png'...
[3/3] Retrying to download 'http://himawari8.nict.go.jp/img/D531106/4d/550/2017/07/25/201000_0_3.png'...
Exception in thread himawaripy-main-thread:
Traceback (most recent call last):
  File "/usr/lib/python3.5/urllib/request.py", line 1254, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/usr/lib/python3.5/http/client.py", line 1106, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python3.5/http/client.py", line 1151, in _send_request
    self.endheaders(body)
  File "/usr/lib/python3.5/http/client.py", line 1102, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python3.5/http/client.py", line 934, in _send_output
    self.send(msg)
  File "/usr/lib/python3.5/http/client.py", line 877, in send
    self.connect()
  File "/usr/lib/python3.5/http/client.py", line 849, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/usr/lib/python3.5/socket.py", line 693, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/usr/lib/python3.5/socket.py", line 732, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.5/dist-packages/himawaripy-2.0.1-py3.5.egg/himawaripy/__main__.py", line 156, in thread_main
    res = p.map(download_chunk, it.product(range(level), range(level), (requested_time,), (args.level,)))
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 260, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 608, in get
    raise self._value
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/usr/local/lib/python3.5/dist-packages/himawaripy-2.0.1-py3.5.egg/himawaripy/__main__.py", line 60, in download_chunk
    tiledata = download(url)
  File "/usr/local/lib/python3.5/dist-packages/himawaripy-2.0.1-py3.5.egg/himawaripy/__main__.py", line 132, in download
    raise exception
  File "/usr/local/lib/python3.5/dist-packages/himawaripy-2.0.1-py3.5.egg/himawaripy/__main__.py", line 123, in download
    with urllib.request.urlopen(url) as response:
  File "/usr/lib/python3.5/urllib/request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 466, in open
    response = self._open(req, data)
  File "/usr/lib/python3.5/urllib/request.py", line 484, in _open
    '_open', req)
  File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 1282, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/usr/lib/python3.5/urllib/request.py", line 1256, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno -3] Temporary failure in name resolution>
```

@boramalper any idea what to do? In the beginning I thought this could be a problem with the source, but the error happens regularly....

**Comment by boramalper** [comment]
Closing the issue due to inactivity (+ frankly I don't know how to approach this either, feels like a problem with *your* machine's network access to me). Feel free to open a new issue if the problem persists.
