### ISSUE TITLE
'TypeError("cannot serialize '_io.BufferedReader' object",)'

### ISSUE THREAD

**Issue by ZSandyGhost** [boramalper/himawaripy#72]
``` bash
Updating...
Latest version: 2016/08/05 16:50:00 GMT
Offset version: 2016/08/05 12:08:00 GMT

Downloading tiles: 0/64 completedTraceback (most recent call last):
  File "/usr/local/bin/himawaripy", line 9, in <module>
    load_entry_point('himawaripy==1.1', 'console_scripts', 'himawaripy')()
  File "/usr/local/lib/python3.5/dist-packages/himawaripy-1.1-py3.5.egg/himawaripy/himawaripy.py", line 88, in main
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 260, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 608, in get
    raise self._value
multiprocessing.pool.MaybeEncodingError: Error sending result: '<multiprocessing.pool.ExceptionWithTraceback object at 0x7f9eb1756c50>'. Reason: 'TypeError("cannot serialize '_io.BufferedReader' object",)'
```

I get this error when I run it from terminal. This is the first run. I  got this error on Ubuntu few weeks ago when I first tried it. Now I'm on Mint 18 and getting the same error.

**Comment by boramalper** [comment]
see #63.
